package org.usfirst.frc1982.the2018PracticeBot;

import org.frc1982.common.AutoChooser;
import org.frc1982.common.Goal;
import org.frc1982.common.Position;
import org.frc1982.common.Side;
import org.usfirst.frc1982.the2018PracticeBot.subsystems.Claw;
import org.usfirst.frc1982.the2018PracticeBot.subsystems.Drive;
import org.usfirst.frc1982.the2018PracticeBot.subsystems.DrivePneumatics;
import org.usfirst.frc1982.the2018PracticeBot.subsystems.Elevator;
import org.usfirst.frc1982.the2018PracticeBot.commands.MoveTo;
import org.usfirst.frc1982.the2018PracticeBot.commands.MoveToPID;
import org.usfirst.frc1982.the2018PracticeBot.commands.TurnTo;
import org.usfirst.frc1982.the2018PracticeBot.commands._AutoDoNothing;
import org.usfirst.frc1982.the2018PracticeBot.commands._AutoFarLine;
import org.usfirst.frc1982.the2018PracticeBot.commands._AutoLineCross;
import org.usfirst.frc1982.the2018PracticeBot.commands._AutoSLeftGSwLeft;
import org.usfirst.frc1982.the2018PracticeBot.commands._AutoSMidGSwLeft;
import org.usfirst.frc1982.the2018PracticeBot.commands._AutoSMidGSwRight;
import org.usfirst.frc1982.the2018PracticeBot.commands._AutoSRightGSwRight;

import com.ctre.phoenix.motorcontrol.NeutralMode;

import edu.wpi.first.wpilibj.CameraServer;
import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.TimedRobot;
import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.command.CommandGroup;
import edu.wpi.first.wpilibj.command.Scheduler;
import edu.wpi.first.wpilibj.smartdashboard.SendableChooser;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

/**
 * The VM is configured to automatically run this class, and to call the
 * functions corresponding to each mode, as described in the TimedRobot
 * documentation. If you change the name of this class or the package after
 * creating this project, you must also update the build.properties file in 
 * the project.
 */
public class Robot extends TimedRobot {

    Command autonomousCommand;
    public static ADIS16448_IMU gyro;
//    public static boolean gyroValid;
//    public static boolean useGyroForAuto = false;
//    public static final int max_velocity = 100;
    
    
    public static OI oi;
    public static Drive drive;
    public static DrivePneumatics pneumatics;
    public static Claw claw;
    public static Elevator elevator;
    SendableChooser<Position> StartPos= new SendableChooser<>();
    SendableChooser<Command> chooser = new SendableChooser<Command>();

    /**
     * This function is run when the robot is first started up and should be
     * used for any initialization code.
     */
    @Override
    public void robotInit() {
        RobotMap.init();
        drive = new Drive();
        pneumatics = new DrivePneumatics();
        claw = new Claw();
        elevator = new Elevator();
        
        // OI must be constructed after subsystems. If the OI creates Commands
        //(which it very likely will), subsystems are not guaranteed to be
        // constructed yet. Thus, their requires() statements may grab null
        // pointers. Bad news. Don't move it.
        oi = new OI();

        // Add commands to Autonomous Sendable Chooser
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=AUTONOMOUS

        chooser.addDefault("Auto Do Nothing", new _AutoDoNothing());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=AUTONOMOUS
        chooser.addObject("MoveTo", new MoveToPID(60));
        chooser.addObject("TurnLeft", new TurnTo(-90.0));
        chooser.addObject("TurnRight", new TurnTo(90.0));
        chooser.addObject("AutoLine", new _AutoLineCross());
        chooser.addObject("AutoSMidGSwLeft", new _AutoSMidGSwLeft());
        chooser.addObject("AutoSMidGSwRight", new _AutoSMidGSwRight());
        chooser.addObject("AutoSLeftGSwLeft", new _AutoSLeftGSwLeft());
        chooser.addObject("AutoSRightGSwRight", new _AutoSRightGSwRight());
        SmartDashboard.putData("Auto mode", chooser);
        
        gyro = new ADIS16448_IMU();
        
//        gyro.calibrate(); //already done in constructor
        gyro.reset();
        
        RobotMap.driveRight.setNeutralMode(NeutralMode.Brake);
        RobotMap.driveLeft.setNeutralMode(NeutralMode.Brake);
        
//        PowerDistributionPanel pdp = new PowerDistributionPanel();
//        SmartDashboard.putData(pdp);
//        
//        SmartDashboard.putBoolean("Only Generate Autonomous", true);
        
        CameraServer.getInstance().startAutomaticCapture();
        
        StartPos.addDefault("Middle", Position.MID);
        StartPos.addObject("Left", Position.LEFT);
        StartPos.addObject("Right", Position.RIGHT);
        
        SmartDashboard.putData("Start Position", StartPos);
        SmartDashboard.putBoolean("Do Switch?", true);
        SmartDashboard.putBoolean("Do Scale?", true);
        SmartDashboard.putBoolean("Do Line?", true);
        SmartDashboard.putBoolean("Prioritize switch?", false);
        
        
        
    }

    /**
     * This function is called when the disabled button is hit.
     * You can use it to reset subsystems before shutting down.
     */
    @Override
    public void disabledInit(){
    }
    
    @Override
    public void disabledPeriodic() {
        Scheduler.getInstance().run();
        //TODO: uncomment (and test)
        parseGameData(DriverStation.getInstance().getGameSpecificMessage());
    }
    
    private Goal goal;
    private Side targetSide;
    private char startingPos;
    
    public boolean parseGameData(String GameData) {
    	//delete once wyatt makes the thing
    	if (oi.opBox.getRawButton(5)) {
    		startingPos = 'L';
    	} else if (oi.opBox.getRawButton(4)) {
    		startingPos = 'R';
    	} else {
    		startingPos = 'M';
    	}
    	boolean switchSwSc = true;
    	boolean Sw = oi.opBox.getRawButton(2);
    	boolean Sc = oi.opBox.getRawButton(3);
    	boolean Line = oi.opBox.getRawButton(1);
    	//if the gamedata actually has something useful:
    	if (GameData.length() > 0) {
//    		System.out.println("GameData: " + GameData);
    		if (!switchSwSc) { //if we are following the normal priority list:
    			if (Sc && GameData.charAt(1) == startingPos) {
    				goal = Goal.SCALE;
    				if (startingPos == 'L') targetSide = Side.LEFT;
    				else if (startingPos == 'R') targetSide = Side.RIGHT;
    				return true;
    			} else if (Sw && ((startingPos == 'M') || (startingPos == GameData.charAt(0)))) {
    				goal = Goal.SWITCH;
   					if (GameData.charAt(0) == 'L') targetSide = Side.LEFT;
   					else if (GameData.charAt(0) == 'R') targetSide = Side.RIGHT;
    				return true;
    			} else if (Line) {
    				goal = Goal.LINE;
    				return true;
    			} else {
    				goal = Goal.NOTHING;
    				return true;
    			}
    		} else { //if we are switching the switch (heh) and scale position in the priority list
    			if (Sw && ((startingPos == 'M') || (startingPos == GameData.charAt(0)))) {
    				goal = Goal.SWITCH;
    				if (GameData.charAt(0) == 'L') targetSide = Side.LEFT;
    				else if (GameData.charAt(0) == 'R') targetSide = Side.RIGHT;
    				return true;
    			} else if (Sc && GameData.charAt(1) == startingPos) {
    				goal = Goal.SCALE;
    				if (startingPos == 'L') targetSide = Side.LEFT;
    				else if (startingPos == 'R') targetSide = Side.RIGHT;
    				return true;
    			} else if (Line) {
    				goal = Goal.LINE;
    				return true;
    			} else {
    				goal = Goal.NOTHING;
    				return true;
    			}
    			
    		}
    	}
    	return false;
    }
    
    
    @Override
    public void autonomousInit() {
    	RobotMap.pneumaticsGearShifter.set(DoubleSolenoid.Value.kReverse);
    	RobotMap.driveRight.setSelectedSensorPosition(0, 0, 0);
    	RobotMap.driveLeft.setSelectedSensorPosition(0, 0, 0);
//        autonomousCommand = new _AutoGeneral(AutoChooser.getAutoPath(StartPos.getSelected(), goal, targetSide), goal);
//    	autonomousCommand = new _AutoSLeftGSwLeft();
    	
        autonomousCommand = chooser.getSelected();
//    	autonomousCommand = getAuto();
    	
        if (autonomousCommand != null) {
        	autonomousCommand.start();
        }
    }

    //uses startingPos, goal, and targetSide
    private Command getAuto() {
    	switch(goal) {
    	case SWITCH:
    		//goal is switch:
    		if (startingPos == 'M') {
    			//starting in middle:
    			if (targetSide == Side.LEFT) {
    				System.out.println("AutoSMidGSwLeft");
    				return new _AutoSMidGSwLeft();
    			} else {
    				System.out.println("AutoSMidGSwRight");
    				return new _AutoSMidGSwRight();
    			}
    		} else if (startingPos == 'L') {
    			//starting on the left:
    			if (targetSide == Side.LEFT) {
    				System.out.println("AutoSLeftGSwLeft");
    				return new _AutoSLeftGSwLeft();
    			} else {
    				System.out.println("AutoFarLineCross");
    				return new _AutoFarLine();
    			}
    		} else {
    			//starting on the right:
    			if (targetSide==Side.RIGHT) {
    				System.out.println("AutoSRightSwRight");
    				return new _AutoSRightGSwRight();
    			} else {
    				System.out.println("AutoFarLineCross");
    				return new _AutoFarLine();
    			}
    		}
    	case SCALE:
    		System.out.println("Goal is scale; not running auto, you done goofed");
    		break;
    	case LINE:
    		System.out.println("Running Auto Line Cross");
    		return new _AutoLineCross();
		default:
			System.out.println("Doing nothing");
    		return new _AutoDoNothing();
    	}
    	return new _AutoDoNothing();
    }
    
    /**
     * This function is called periodically during autonomous
     */
    @Override
    public void autonomousPeriodic() {
        Scheduler.getInstance().run();
    }

    @Override
    public void teleopInit() {
        // This makes sure that the autonomous stops running when
        // teleop starts running. If you want the autonomous to
        // continue until interrupted by another command, remove
        // this line or comment it out.
        if (autonomousCommand != null) autonomousCommand.cancel();
        RobotMap.pneumaticsGearShifter.set(DoubleSolenoid.Value.kReverse);
        RobotMap.driveLeft.setSelectedSensorPosition(0, 0, 0);
        RobotMap.driveRight.setSelectedSensorPosition(0, 0, 0);
    }

    /**
     * This function is called periodically during operator control
     */
    @Override
    public void teleopPeriodic() {
        Scheduler.getInstance().run();
    }
}
