// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1982.the2014Bot;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.Jaguar;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SpeedController;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
//    public static SpeedController driveTrainLeft;
//    public static SpeedController driveTrainRight;
//    public static RobotDrive driveTraindriveTrain;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
//        driveTrainLeft = new Jaguar(1);
//        LiveWindow.addActuator("DriveTrain", "Left", (Jaguar) driveTrainLeft);
//        driveTrainLeft.setInverted(false);
//        driveTrainRight = new Jaguar(2);
//        LiveWindow.addActuator("DriveTrain", "Right", (Jaguar) driveTrainRight);
//        driveTrainRight.setInverted(false);
//        driveTraindriveTrain = new RobotDrive(driveTrainLeft, driveTrainRight);
//        
//        driveTraindriveTrain.setSafetyEnabled(true);
//        driveTraindriveTrain.setExpiration(0.1);
//        driveTraindriveTrain.setSensitivity(0.5);
//        driveTraindriveTrain.setMaxOutput(1.0);


        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
