// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1982.the2014Bot.commands;

import edu.wpi.first.wpilibj.command.CommandGroup;
import org.usfirst.frc1982.the2014Bot.subsystems.*;

/**
 *
 */
public class _AutoDoNothing extends CommandGroup {


    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PARAMETERS
    public _AutoDoNothing() {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PARAMETERS
        // Add Commands here:
        // e.g. addSequential(new Command1());
        //      addSequential(new Command2());
        // these will run in order.

        // To run multiple commands at the same time,
        // use addParallel()
        // e.g. addParallel(new Command1());
        //      addSequential(new Command2());
        // Command1 and Command2 will run in parallel.

        // A command group will require all of the subsystems that each member
        // would require.
        // e.g. if Command1 requires chassis, and Command2 requires arm,
        // a CommandGroup containing them would require both the chassis and the
        // arm.
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS
    	System.out.println("This statement was called at: " + System.currentTimeMillis());
    }
    
    // Can be overwritten by teams
    protected void initialize() {
    	System.out.println("AutoDoNothing Started");
    }
    
    protected void end() {
    	System.out.println("Autonomous has ended (as a result of end method)");
    }
    
    protected void interrupted() {
    	System.out.println("Autonomous has ended (as a result of interrupted method)");
    }
    
}
