
package org.usfirst.frc1982.the2018Bot;

import com.ctre.phoenix.ParamEnum;
import com.ctre.phoenix.motorcontrol.FeedbackDevice;
import com.ctre.phoenix.motorcontrol.LimitSwitchNormal;
import com.ctre.phoenix.motorcontrol.LimitSwitchSource;
import com.ctre.phoenix.motorcontrol.RemoteLimitSwitchSource;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;

import edu.wpi.first.wpilibj.Compressor;
import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.Solenoid;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;
import edu.wpi.first.wpilibj.drive.DifferentialDrive;


/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    
    public static SpeedController driveleftSlave;
    public static SpeedController driverightSlave;
    public static Compressor pneumaticsCompressor;
    public static DoubleSolenoid pneumaticsGearShifter;
    
    //claw solenoids:
    public static DoubleSolenoid pneumaticsClaw;
    public static DoubleSolenoid pneumaticsPunch;
    public static DoubleSolenoid pneumaticsHinge;
    
    public static WPI_TalonSRX driveRight;
    public static WPI_TalonSRX driveLeft;
    
    public static WPI_TalonSRX elevatorLeft;
    public static WPI_TalonSRX elevatorRight;
    public static void init() {
        
        
        
        driveleftSlave = new Talon(0);
        driveleftSlave.setInverted(true);
        driverightSlave = new Talon(1);
        driverightSlave.setInverted(false);
        
        pneumaticsCompressor = new Compressor(0);
        
        pneumaticsGearShifter = new DoubleSolenoid(0, 0, 1);
        pneumaticsClaw = new DoubleSolenoid(0,2,3);
        pneumaticsPunch = new DoubleSolenoid(0,4,5);
        pneumaticsHinge = new DoubleSolenoid(0,6,7);
        
        //drive talonSRXs
        driveRight = new WPI_TalonSRX(2);
        
        driveRight.configSelectedFeedbackSensor(FeedbackDevice.CTRE_MagEncoder_Relative, 0, 20);
        driveRight.setSelectedSensorPosition(0,0,0);
        driveRight.setSensorPhase(false);
        
        driveLeft = new WPI_TalonSRX(1);
        
        driveLeft.configSelectedFeedbackSensor(FeedbackDevice.CTRE_MagEncoder_Relative, 0, 20);
        driveLeft.setSelectedSensorPosition(0,0,0);
        driveLeft.setSensorPhase(false);
        
        driveLeft.setInverted(true);
        driveRight.setInverted(false);
        
        driveRight.setSafetyEnabled(false);
        driveLeft.setSafetyEnabled(false);
        
        //elevator TalonSRXs:
        elevatorLeft = new WPI_TalonSRX(3);
        
        elevatorRight = new WPI_TalonSRX(4);
        
        elevatorRight.configSelectedFeedbackSensor(FeedbackDevice.CTRE_MagEncoder_Relative,0,20);
        elevatorRight.setSensorPhase(false);
        elevatorRight.setSelectedSensorPosition(0, 0, 0);
        
        elevatorRight.configReverseLimitSwitchSource(LimitSwitchSource.FeedbackConnector, LimitSwitchNormal.NormallyOpen, 0);
        elevatorRight.configSetParameter(ParamEnum.eClearPositionOnLimitR, 1, 0, 0, 0);
        
        elevatorRight.config_kP(0, 0.1, 0);
        elevatorRight.config_kI(0, 0, 0);
        elevatorRight.config_kD(0, 0, 0);
        elevatorRight.config_kF(0, 0, 0);
        
        System.out.println(elevatorLeft.configReverseLimitSwitchSource(RemoteLimitSwitchSource.RemoteTalonSRX, LimitSwitchNormal.NormallyOpen, 4, 0));
        elevatorLeft.follow(elevatorRight);
    }
}