
package org.usfirst.frc1982.the2018Bot;

import com.ctre.phoenix.motorcontrol.FeedbackDevice;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;

import edu.wpi.first.wpilibj.Compressor;
import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;
import edu.wpi.first.wpilibj.drive.DifferentialDrive;


/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    
    public static SpeedController driveleftSlave;
    public static SpeedController driverightSlave;
    public static Compressor pneumaticsCompressor;
    public static DoubleSolenoid pneumaticsGearShifter;

    public static WPI_TalonSRX driveRight;
    public static WPI_TalonSRX driveLeft;
//    public static DifferentialDrive driveTrain;
    public static void init() {
        
        
        
        driveleftSlave = new Talon(0);
        driveleftSlave.setInverted(true);
        driverightSlave = new Talon(1);
        driverightSlave.setInverted(false);
        
        
        pneumaticsCompressor = new Compressor(0);
        
        pneumaticsGearShifter = new DoubleSolenoid(0, 0, 1);
        
        driveRight = new WPI_TalonSRX(2);
        
        driveRight.configSelectedFeedbackSensor(FeedbackDevice.CTRE_MagEncoder_Relative, 0, 20);
        driveRight.setSelectedSensorPosition(0,0,0);
        driveRight.setSensorPhase(false);
        
        driveLeft = new WPI_TalonSRX(1);
        
        driveLeft.setInverted(true);
        driveRight.setInverted(false);
        
        driveRight.setSafetyEnabled(false);
        driveLeft.setSafetyEnabled(false);
        
//        driveTrain = new DifferentialDrive(driveLeft,driveRight);
    }
}
